//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_LapTop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public HangHoa()
        {
            this.ChiTietHDBans = new HashSet<ChiTietHDBan>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string MaLoaiHang { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public string AnhBia { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<ChiTietHDBan> ChiTietHDBans { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
    }
}
