//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_LapTop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHang
    {
        public LoaiHang()
        {
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public string MaLoaiHang { get; set; }
        public string TenLoaiHang { get; set; }
        public string MaNhaCC { get; set; }
        public string MaTTBaoHanh { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual TrungTamBaoHanh TrungTamBaoHanh { get; set; }
    }
}
