//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_LapTop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDBan
    {
        public string MaHDBan { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> SLBan { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public string MaNhanVien { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
